/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IENS, IENSInterface } from "../../OpenDID.sol/IENS.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "node",
        "type": "bytes32"
      }
    ],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "node",
        "type": "bytes32"
      }
    ],
    "name": "resolver",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IENS__factory {
    static readonly abi = _abi;
    static createInterface(): IENSInterface {
      return new Interface(_abi) as IENSInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IENS {
      return new Contract(address, _abi, runner) as unknown as IENS;
    }
  }
  