/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as proofOfMeSol from './ProofOfMe.sol/index.js';
export { CredentialRegistry__factory } from './CredentialRegistry__factory.js';