/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IENS } from './IENS.js';
export type { IENSResolver } from './IENSResolver.js';
export type { ProofOfMe } from './ProofOfMe.js';