/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'CredentialRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CredentialRegistry__factory>
getContractFactory(name: 'IENS', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IENS__factory>
getContractFactory(name: 'IENSResolver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IENSResolver__factory>
getContractFactory(name: 'ProofOfMe', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ProofOfMe__factory>

  getContractAt(name: 'CredentialRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CredentialRegistry>
getContractAt(name: 'IENS', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IENS>
getContractAt(name: 'IENSResolver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IENSResolver>
getContractAt(name: 'ProofOfMe', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ProofOfMe>

  deployContract(name: 'CredentialRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CredentialRegistry>
deployContract(name: 'IENS', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IENS>
deployContract(name: 'IENSResolver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IENSResolver>
deployContract(name: 'ProofOfMe', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ProofOfMe>

  deployContract(name: 'CredentialRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CredentialRegistry>
deployContract(name: 'IENS', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IENS>
deployContract(name: 'IENSResolver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IENSResolver>
deployContract(name: 'ProofOfMe', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ProofOfMe>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  