/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proofOfMeSol from './ProofOfMe.sol/index.js';
export type { proofOfMeSol };
export type { CredentialRegistry } from './CredentialRegistry.js';
export * as factories from './factories/index.js';
export { CredentialRegistry__factory } from './factories/CredentialRegistry__factory.js';
export type { IENS } from './ProofOfMe.sol/IENS.js';
export { IENS__factory } from './factories/ProofOfMe.sol/IENS__factory.js';
export type { IENSResolver } from './ProofOfMe.sol/IENSResolver.js';
export { IENSResolver__factory } from './factories/ProofOfMe.sol/IENSResolver__factory.js';
export type { ProofOfMe } from './ProofOfMe.sol/ProofOfMe.js';
export { ProofOfMe__factory } from './factories/ProofOfMe.sol/ProofOfMe__factory.js';